name: Run lint, test and build

on: pull_request
jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - run: yarn
      - run: yarn lint:check

      - run: yarn test

      - run: yarn build
